# version: '3.1'
 
# services:
#   db:
#     image: mysql:latest
#     container_name: db
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: usersd
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     ports:
#       - "6033:3306"
#     volumes:
#       - dbdata:/var/lib/mysql
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     container_name: pma
#     links:
#       - db
#     environment:
#       PMA_HOST: db
#       PMA_PORT: 3306
#       PMA_ARBITRARY: 1
#     restart: always
#     ports:
#       - 8081:80
# volumes:
#   dbdata:

 version: '3.1'
 services:
  #  node:
  #    build: 
  #      dockerfile: ./Dockerfile
  #      context: .
  #    image: node:latest
  #    container_name: api
  #    restart: always
  #    working_dir: /app
  #    volumes:
  #      - ./:/app
  #    ports:
  #      - 3000:3000
  #    depends_on:
  #      - "database"
   database:
     image: mysql:latest
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: usersdb
     ports:
       - "33060:3306"
     volumes:
       - ./database.sql:/docker-entrypoint-initdb.d/database.sql